---
# handlers file for sshd-role
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
    daemon_reload: true
    enabled: true
