- name: Copy files
  ansible.builtin.copy:
    src: "crs.tar.gz"
    dest: "/etc/"
    owner: root
    group: root

- name: Unarchive crs
  ansible.builtin.unarchive:
    remote_src: true
    src: /etc/crs.tar.gz
    dest: /etc/

- name: Remove archive
  ansible.builtin.file:
    path: /etc/crs.tar.gz
    state: absent

- name: Rule to allow webapp to work
  ansible.builtin.lineinfile:
    line: "    SecRuleRemoveById 920350"
    insertafter: "^<IfModule mod_security2.c>"
    state: present
    path: "/etc/httpd/conf.d/mod_security.conf"

- name: Edit mod_security.conf
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE CSR BLOCK"
    block: |
      IncludeOptional /etc/crs/crs-setup.conf                               
      IncludeOptional /etc/crs/plugins/*-config.conf                               
      IncludeOptional /etc/crs/plugins/*-before.conf                               
      IncludeOptional /etc/crs/rules/*.conf                               
      IncludeOptional /etc/crs/plugins/*-after.conf 
    insertbefore: "^<IfModule.*"
    state: present
    path: /etc/httpd/conf.d/mod_security.conf

   
