#SPDX-License-Identifier: MIT-0
---
# tasks file for AIDE-role

- name: Task1
  ansible.builtin.import_tasks: install-aide.yaml

- name: Task2
  ansible.builtin.include_tasks: database-aide.yaml
  when: "'_database' in group_names"

- name: Task3
  ansible.builtin.include_tasks: bastion-aide.yaml
  when: "'_bastion' in group_names"

- name: Task4
  ansible.builtin.include_tasks: webserver-aide.yaml
  when: "'_webserver' in group_names"
