- name: Create mariadb Service
  ansible.builtin.template:
    src: mariadb.xml.j2
    dest: /etc/firewalld/services/mariadb.xml
    owner: root
    group: root
    mode: '0644'

- name: Create sshd service file
  ansible.builtin.template:
    src: sshd.xml.j2
    dest: '/etc/firewalld/services/sshd.xml'
    mode: '0644'
    owner: root
    group: root

- name: Create new zone
  ansible.builtin.template:
    src: database-zone.xml.j2
    dest: /etc/firewalld/zones/database-zone.xml
    mode: '0644'
    owner: root
    group: root
