#SPDX-License-Identifier: MIT-0
---
# tasks file for sysctl-role

- name: Setup webserver sysctl
  ansible.builtin.include_tasks: webserver_server.yaml
  when: "'_webserver' in group_names"

- name: Setup database sysctl
  ansible.builtin.include_tasks: database_server.yaml
  when: "'_database' in group_names"

- name: Setup bastion sysctl 
  ansible.builtin.include_tasks: bastion_server.yaml
  when: "'_bastion' in group_names"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
