- name: Copy scripts
  ansible.builtin.copy:
    src: "scripts/database/"
    dest: "/scripts/"
    owner: root
    group: root
    mode: '0744'


- name: Run basic-update.sh
  ansible.builtin.cron:
    day: "*/15"
    hour: 04
    minute: 00
    name: "Basic Update - No Kernel / MariaDB"
    state: present
    user: root
    job: /scripts/basic-update.sh
